// AUTH
export const LOGIN = 'LOGIN';
export const GET_USERS = 'GET_USERS';
export const LOGOUT = 'LOGOUT';
export const ADD_USER_QUESTION = 'ADD_USER_QUESTION';
export const ADD_USER_QUESTION_ANSWER = 'ADD_USER_QUESTION_ANSWER';
// QUESTIONS
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_QUESTION = 'GET_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const SOLVE_QUESTION = 'SOLVE_QUESTION';
